config/routes.rb
Myapp::Application.routes.draw do
  root to: 'home#index'

  resources :users
  get "/sign_up" => "users#new"

  resources :sessions, only: [:new, :create, :destroy]

  get "/sign_in" => "sessions#new"
  delete "/sign_out" => "sessions#destroy"
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, format: { with: VALID_EMAIL }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  has_secure_password

  before_save :email_in_small
  before_create :create_remember_token

  def email_in_small
    self.email = email.downcase
  end

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt_remember_token(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt_remember_token(User.new_remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in(user, params[:remember_me])
      redirect_to root_path, :notice => "Signed in successfully."
    else
      flash[:error] = "Invalid email or password combination."
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user, remember_me=nil)
    remember_token = User.new_remember_token
    if remember_me
      cookies.permanent[:remember_token] = remember_token
    else
      cookies[:remember_token] = remember_token
    end
    user.update_attribute(:remember_token, User.encrypt_remember_token(remember_token))
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt_remember_token(cookies[:remember_token])
    @current_user ||= User.find_by_remember_token(remember_token)
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
end

app/views/home/index.html.erb
Welcome to Santanu's Profile
<p><%= link_to "Sign Up", sign_up_path unless current_user %></p>
<p><%= link_to "Sign In", sign_in_path unless current_user %></p>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <ul class="nav">
        <li><%= link_to "Home", root_path %></li>
        <% if signed_in? %>
          <li><%= link_to "Sign Out", sign_out_path, method: 'delete' %></li>
        <% else %>
          <li><%= link_to "Sign Up", sign_up_path %></li>
          <li><%= link_to "Sign In", sign_in_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  The form contains <%= @user.errors.count %> errors.
  <% @user.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>

  <% end %>
<% end %>

app/views/users/new.html.erb
<h2>Sign Up</h2>
<div class="row">
  <%= form_for @user do |f| %>
  <%= render 'shared/error_messages' %>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit "Create my account" %>
  </p>
  <% end %>
</div>